spring:
  datasource:
    url: jdbc:mysql://localhost:13306/car-rental
    username: root
    password: bc123
  jpa:
    generate-ddl: true
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 9090

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE